### ISSUE TITLE
Remove Total column and row

### ISSUE THREAD

**Issue by Chris-M-P** [jalvesaq/descr#2]
Would it be possible to add an option to suppress the Total column and row?

**Comment by jalvesaq** [comment]
It's possible. I will look at this soon.

**Comment by jalvesaq** [comment]
I implemented the options in the following way:

  - `total.r`: If `TRUE`, print row totals.
  - `total.c`: If `TRUE`, print column totals.

If both arguments `total.c` and `total.r` are missing, both will be `TRUE`. If only one of them is missing, it will have the value of the not missing. So, if you don't want totals, you just need to pass one argument.

If you think that it is best to keep the two arguments completely independent of each other, I can change this. That is, to not print any total, you would have to do pass to `CrossTable`:

```r
total.r = FALSE, total.c = FALSE,
```

**Comment by Chris-M-P** [comment]
This works fine, but seems to have broken compatibility with the `pander` package. I now get this error:
`Error in matrix(paste(xx, "%", sep = ""), nrow = nr, ncol = nc + 1) : `
 ` non-numeric matrix extent`

After running a `CrossTable` object through `pander`

**Comment by jalvesaq** [comment]
I did not know that the `CrossTable` object (which is a list) was used by *pander*. I had renamed the list element `t` as `tab`. But now I added the `t` back to the list as a copy of `tab`: https://github.com/jalvesaq/descr/commit/3f6c60fb1db3b80bb5445e7245665c0a0cb73eb0

Note: *pander* adds the `%` symbol to both row headers and cell contents. This is redundant.

**Comment by Chris-M-P** [comment]
It's working fine with `pander` now, thanks. Although `pander` reinserts the row and column totals! But that doesn't seem to be an issue with `descr`.

**Comment by jalvesaq** [comment]
If *pander*'s author wants to add support `to total.c` and `total.r`, he may want to look at the function `CreateNewTab` in *CrossTable.R*.
