### ISSUE TITLE
Include.rownames option not supported

### ISSUE THREAD

**Issue by elinw** [jalvesaq/descr#5]
Normally in xtable you can have   `include.rownames = FALSE`
But this code
https://github.com/jalvesaq/descr/blob/master/R/xtable.R#L26
```
nt <- cbind(rownames(nt), nt)
```
Is making it so that having the row names can't be not included. Therefore you have to do the following to get rid of them
```
print(xtable(ctobject),
      include.rownames = getOption("xtable.include.rownames", FALSE))
```
What do you think about making that line conditional on the include.rownames option?

**Comment by jalvesaq** [comment]
The `include.rownames` argument works only with

**Comment by jalvesaq** [comment]
The `include.rownames` argument works only with `print.xtable`:

```r
library("xtable")
data(tli)
xtable(tli[1:20, ])
xtable(tli[1:20, ], include.rownames = FALSE)
print(xtable(tli[1:20, ]), include.rownames = FALSE)
```

If I do not convert the row names into a column, the "expected" lines would have repeated rownames in this code:

```r
library("xtable")
library("descr")
data(tli)
ctobj <- crosstab(tli$ethnicty, tli$disadvg, expected = TRUE)
ctobj
```

All other statistics (`resid`, `asresid`, etc.) would also have repeated row names.

**Comment by elinw** [comment]
But it actually doesn't work that way for the crosstables ..  this should work but it doesn't.
```
print(xtable(ctobj, include.rownames=FALSE))
```

**Comment by jalvesaq** [comment]
Try this:

```r
print(xtable(ctobj), include.rownames=FALSE)
```

**Comment by elinw** [comment]
Yes!!! Thanks!
